- hosts: all
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true

- hosts: all
  become: true
  tasks:
    - name: Install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: latest
        fail_on_autoremove: no

- hosts: all
  tasks:
    - name: Create APP Directory
      file: path=/usr/local/src/app state=directory

    - name: Copy source file
      get_url:
        url: https://github.com/lacework-demo/ticketing-app/releases/download/latest/tickets.tgz
        dest: /usr/local/src/app/app.tgz
        mode: '0440'

    - name: Extract archive
      ansible.builtin.unarchive:
        src: /usr/local/src/app/app.tgz
        dest: /usr/local/src/app/
        copy: no

- hosts: all
  become: yes
  roles:
    - weareinteractive.pm2
  vars:
    pm2_user: root
    pm2_upstart: no
    pm2_apps:
       - run: index.js
         cmd: start
         args: --name app
         path: /usr/local/src/app
         env:
          PORT: "{{ datalayer_port }}"
          MONGODB_CONN_STRING: "{{ mongodb_conn_string }}"
          MONGODB_USER: "{{ mongodb_user }}"
          MONGODB_PASS: "{{ mongodb_pass }}"
    pm2_apps_default_env:
      NODE_ENV: production
